### PR TITLE
wrong links redirected to home page

### PR DESCRIPTION
**Pull request by patelaryan7751**
I have added a .htaccess file which would redirect any wrong links to home page

[link to the issue](https://github.com/Harshal0902/Rudra/issues/46)

### CODE REVIEW

**Review by Harshal0902 — CHANGES_REQUESTED** [review]
@patelaryan7751 as the issue is of Level 2, kindly make a 404 not found page. If a user visits a wrong link, redirect it to the 404 not found page, and add a button to redirect it to the home page.

**Comment by patelaryan7751** [comment]
> @patelaryan7751 as the issue is of Level 2, kindly make a 404 not found page. If a user visits a wrong link, redirect it to the 404 not found page, and add a button to redirect it to the home page.

okay

**Comment by patelaryan7751** [comment]
@Harshal0902 I added a 404 page with the above said changes.

**Review by Harshal0902 — APPROVED** [review]
@patelaryan7751 good work

**Pull request merged**
