### PR TITLE
Steps for deploying a static app to digital ocean

### PR DESCRIPTION
**Pull request by ghost**
I wrote a guide for the deployment of a static app to DigitalOcean, enumerated the steps, and provided the tips and applicable screenshots to the process

### CODE REVIEW

**Comment by Harshal0902** [comment]
@nelsonkimani63 great work, just place all the necessary files and folder under the **Guides/ directory**

**Comment by nelsonguya** [comment]
Hi @Harshal0902
Done.

**Comment by Harshal0902** [comment]
@nelsonkimani63 just place the DigitalOcean.md files under the **Guides/** directory

**Comment by nelsonguya** [comment]
Hi @Harshal0902
All files of DigitalOcean.md are now in the guides directory. Thanks

**Review by Harshal0902 — APPROVED** [review]
@nelsonkimani63 good work

**Pull request merged**
