### PR TITLE
Updated Home Page Article to clickable

### PR DESCRIPTION
**Pull request by ajaydr16**
#59 
for LGMSOC21 

Now updated to clickable.

### CODE REVIEW

**Review by Harshal0902 — APPROVED** [review]
@ajaydr16 good work.

**Comment by Harshal0902** [comment]
@ajaydr16 kindly resolve the conflicts so that I can merge this PR.

**Comment by ajaydr16** [comment]
@Harshal0902 
How to resolve these conflicts?
I see it is showing conflicts like onload="loader()" it's calling some javascript function loader()
but I didn't do any changes to javascript.

**Comment by Harshal0902** [comment]
Your branch is some commit behind the original repo. please follow the steps in CONTRIBUTING.md to update it.

**Comment by ajaydr16** [comment]
Sorry, I deleted my repo by trying to solve this.
I have created another pull request.

**Pull request closed without merging**
